-- 코드를 입력하세요
# 2022년 1월의 
# 도서 판매 데이터를 기준으로 
# author 별, (TOTAL_SALES = 판매량 * 판매가)
# category 별 매출액 (TOTAL_SALES = 판매량 * 판매가)

# 저자 ID(AUTHOR_ID), 
# 저자명(AUTHOR_NAME), 
# 카테고리(CATEGORY), 
# 매출액(SALES) 리스트를 출력


# SELECT DATE_FORMAT(SALES_DATE, '%Y-%m')
# FROM BOOK_SALES
# WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01';

-- double group by

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A ON (B.AUTHOR_ID = A.AUTHOR_ID)
JOIN BOOK_SALES BS ON (B.BOOK_ID = BS.BOOK_ID)
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC
;

