-- 코드를 작성해주세요
# ROOT 아이템을 찾아
# 아이템 ID(ITEM_ID), 아이템 명(ITEM_NAME)을 출력
# 결과는 아이템 ID를 기준으로 오름차순 정렬

SELECT II.ITEM_ID, II.ITEM_NAME
FROM ITEM_INFO II
JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID
AND IT.PARENT_ITEM_ID IS NULL
ORDER BY II.ITEM_ID;


