-- 코드를 입력하세요
# 입양을 간 기록은 있는데 (O)
# 보호소에 들어온 기록이 없는 (I)
# 동물의 ID와 이름
# ID 순으로 조회

# SELECT O.ANIMAL_ID, O.NAME
# FROM ANIMAL_INS I
# JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.NAME IS NULL
# ORDER BY O.ANIMAL_ID;

# OUTS에 있는데 INS에 없으면 출력
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID;
