-- 코드를 입력하세요
# USER_INFO 테이블과
# ONLINE_SALE 테이블에서
# 2021년에 가입한 전체 회원들 중

# 상품을 구매한 회원수와
# 상품을 구매한 회원의 비율 (=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
# 년, 월 별로 출력

# 상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올림
# 전체 결과는 년을 기준으로 오름차순 정렬
# 년이 같다면 월을 기준으로 오름차순 정렬

-- 상품을 구매한 회원수
SELECT 
    YEAR(OS.SALES_DATE) YEAR
    , MONTH(OS.SALES_DATE) MONTH
    , COUNT(DISTINCT UI.USER_ID) PURCHASED_USERS
    , ROUND(COUNT(DISTINCT UI.USER_ID) / 
    (
        SELECT COUNT(DISTINCT UI.USER_ID) COUNT_MEMBER_21
        FROM USER_INFO UI
        LEFT JOIN ONLINE_SALE OS ON (UI.USER_ID = OS.USER_ID)
        WHERE YEAR(UI.JOINED) = 2021
    ), 1) PURCHASED_RATIO
FROM USER_INFO UI
LEFT JOIN ONLINE_SALE OS ON (UI.USER_ID = OS.USER_ID)
WHERE YEAR(UI.JOINED) = 2021
AND OS.ONLINE_SALE_ID IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
;

-- 전체 회원수 (2021년도)
# SELECT COUNT(DISTINCT UI.USER_ID) COUNT_MEMBER_21
# FROM USER_INFO UI
# LEFT JOIN ONLINE_SALE OS ON (UI.USER_ID = OS.USER_ID)
# WHERE YEAR(UI.JOINED) = 2021
# ;


# SELECT 
    # YEAR(OS.SALES_DATE) YEAR
    # , MONTH(OS.SALES_DATE) MONTH
    
# FROM USER_INFO UI
# LEFT JOIN ONLINE_SALE OS ON (UI.USER_ID = OS.USER_ID)
# WHERE YEAR(UI.JOINED) = 2021
# GROUP BY YEAR, MONTH
# ;

