-- 코드를 작성해주세요
# 각 분기(QUARTER)별 DIFFERENTIATION_DATE
# 대장균의 개체의 총 수(ECOLI_COUNT)를 출력
# 1Q == 1, 2, 3
# 2Q == 4, 5, 6
# 3Q == 7, 8, 9
# 4Q == 10, 11, 12

SELECT QUARTER, COUNT(*) ECOLI_COUNT
FROM 
(
    SELECT 
        CASE
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN '3Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN '4Q'
        END QUARTER
    FROM ECOLI_DATA 
) T
GROUP BY QUARTER
ORDER BY QUARTER
;

