-- 코드를 입력하세요

SELECT T.FLAVOR
FROM (
    SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) + FH.TOTAL_ORDER TOTAL_ORDER
    FROM JULY J
    JOIN FIRST_HALF FH ON J.FLAVOR = FH.FLAVOR
    GROUP BY J.FLAVOR
) T
ORDER BY T.TOTAL_ORDER DESC
LIMIT 3
;

# SELECT FLAVOR, SUM(TOTAL_ORDER)
# FROM JULY J
# GROUP BY FLAVOR;