-- 코드를 입력하세요
# 전화번호가 NULL인 경우는 출력대상에서 제외
# 결과는 회원ID를 기준으로 오름차순 정렬
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS "DATE_OF_BIRTH"
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL
AND DATE_FORMAT(DATE_OF_BIRTH, "%m") = '03'
AND GENDER = 'W'
ORDER BY MEMBER_ID;
