-- 코드를 작성해주세요
# FISH_INFO 테이블에서 잡은 
# BASS와 
# SNAPPER의 수를 출력
# 컬럼명은 'FISH_COUNT`

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FN ON FI.FISH_TYPE = FN.FISH_TYPE
WHERE FN.FISH_NAME LIKE 'BASS' 
OR FN.FISH_NAME LIKE 'SNAPPER';
